// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"database/sql"
)

type Account struct {
	ID        int64       `json:"id"`
	Owner     string      `json:"owner"`
	Balance   int64       `json:"balance"`
	Currency  string      `json:"currency"`
	CreatedAt interface{} `json:"created_at"`
}

type Entry struct {
	ID        int64         `json:"id"`
	AccountID sql.NullInt64 `json:"account_id"`
	// Can be negative or positive
	Amount    int64       `json:"amount"`
	CreatedAt interface{} `json:"created_at"`
}

type Transfer struct {
	ID            int64         `json:"id"`
	FromAccountID sql.NullInt64 `json:"from_account_id"`
	ToAccountID   sql.NullInt64 `json:"to_account_id"`
	// Only positive
	Amount    int64       `json:"amount"`
	CreatedAt interface{} `json:"created_at"`
}
